version: '3.4'

services:
  full:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc:/workdir
    command: >
      sh -c "if [ -f ./diagrams/ArcticDataMapping.png ]; then rm ./diagrams/ArcticDataMapping.png; fi && 
             plantuml_build png -R ./diagrams ./diagrams &&
             asciidoctor -n pdem-datamodel.adoc && 
             asciidoctor-pdf -a pdf-themesdir=./ -a pdf-theme=pdem -n pdem-datamodel.adoc"
