version: '3.4'

services:
  html:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc:/workdir
    command: asciidoctor -n pdem-datamodel.adoc

  pdf:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc:/workdir
    command: asciidoctor-pdf -a pdf-themesdir=./ -a pdf-theme=pdem -n pdem-datamodel.adoc

  puml:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc/diagrams:/workdir
    command: plantuml ArcticDataMapping.puml 
