#
# Docker file used in GitHub Actions to build HTML and PDF
#

FROM ruby:2.7.1-alpine
LABEL maintainer="o.godoy@met.no"

RUN gem install asciidoctor; \
    gem install asciidoctor-pdf --pre; \
    gem install plantuml_builder; \
    mkdir /workdir

VOLUME /workdir
WORKDIR /workdir
